name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 버전 추가
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
          channel: 'stable'
      # 플러터 버전 확인
      - run: flutter --version

      # 의존성 추가
      - name: Install dependencies
        run: flutter pub get

      # 문제점 출력
      # API 키값 숨기는 문제 때문에 주석처리
      # - name: Analyze project source
      #   run: flutter analyze --fatal-infos

      # 테스트 코드 실행
      - name: Run tests
        run: flutter test
        
        
